package view.manager.application;

import dao.imlp.NhanVienDAO;
import dao.imlp.TaiKhoanDAO;
import entity.NhanVien;
import entity.TaiKhoan;
import java.awt.Component;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import raven.toast.Notifications;
import static utils.AppUtils._NORMAL_;
import component.SimpleForm;

public class GD_QuanLyNhanVien extends SimpleForm {

    /**
     * Creates new form ReadForm ([MaNhanVien], [DiaChi], [GioiTinh], [HoTen],
     * [NgayBatDauLam], [SoDienThoai], [TrangThai], [Tuoi], [VaiTro])
     * NVabbddmmyyxxx Trong đó : a là giới tính (nam là 1, nữ là 0) bb là tuổi
     * của nhân viên lúc vào làm dd là ngày vào làm mm là tháng vào làm yy là 2
     * số cuối của năm vào làm xxx là 3 số đuôi của số điện thoại.
     *
     */
    public GD_QuanLyNhanVien() {
        initComponents();

        daoNV = new NhanVienDAO();
        daoTK = new TaiKhoanDAO();

        jTextFieldNgayVaoLam.setEditable(false);
        jTextFieldMaNhanVien.setEditable(false);

        jComboBox1.addItem("Đang làm");
        jComboBox1.addItem("Đã nghĩ làm");
        ButtonGroup group1 = new ButtonGroup();
        group1.add(jRadioButtonNam);
        group1.add(jRadioButtonNu);

        ButtonGroup group2 = new ButtonGroup();
        group2.add(jRadioButtonNhanVienQuanLy);
        group2.add(jRadioButtonNhanVien);
        populateTable();
        autoResizeColumnWidths(jTable1);
    }

    private void populateTable() {
        // Xóa tất cả các dòng hiện có trong bảng
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<NhanVien> allNhanVien = daoNV.findAll(NhanVien.class);

        String gioiTinh = "";
        String trangThai = "";
        // Thêm dữ liệu từ danh sách vào bảng
        for (int i = 0; i < allNhanVien.size(); i++) {
            NhanVien nv = allNhanVien.get(i);
            // Truy cập các thuộc tính của đối tượng Ban và thêm vào từng cột
            if (nv.isGioiTinh()) {
                gioiTinh = "Nữ";
            } else {
                gioiTinh = "Nam";
            }
            if (nv.isTrangThai()) {
                trangThai = "Đang làm";
            } else {
                trangThai = "Đã nghĩ làm";
            }
            model.addRow(new Object[]{i + 1, nv.getHoTen(), nv.getTuoi(), nv.getSoDienThoai(), nv.getNgayBatDauLam().toLocalDate().toString(), gioiTinh, nv.getVaiTro().toString(), trangThai, nv.getMaNV(), nv.getDiaChi()});
        }

        // Tạo renderer tùy chỉnh để căn giữa văn bản
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Gán renderer này cho tất cả các cột
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    private void clearData() {
        jTextFieldHoTen.setText("");
        jTextFieldTuoi.setText("");
        jTextFieldSoDienThoai.setText("");
        jTextFieldNgayVaoLam.setText("");
        jTextFieldDiaChi.setText("");
        jTextFieldMaNhanVien.setText("");
    }

    private void autoResizeColumnWidths(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    private void addTaiKhoan(NhanVien nv) {
        TaiKhoan tk = new TaiKhoan();
        tk.setMatKhau("88888888");
        tk.setNhanVien(nv);
        tk.setNgayTao(LocalDateTime.now());
        tk.setNgayKetThuc(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panelRound2 = new component.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fromDateJLabel = new javax.swing.JLabel();
        panelRound3 = new component.PanelRound();
        hoTen = new javax.swing.JLabel();
        ngayVaoLam = new javax.swing.JLabel();
        tuoi = new javax.swing.JLabel();
        soDienThoai = new javax.swing.JLabel();
        JButtonAdd = new component.MyButton();
        JButtonUpdate = new component.MyButton();
        panelRound4 = new component.PanelRound();
        jTextFieldHoTen = new javax.swing.JTextField();
        panelRound5 = new component.PanelRound();
        jTextFieldSoDienThoai = new javax.swing.JTextField();
        panelRound6 = new component.PanelRound();
        jTextFieldTuoi = new javax.swing.JTextField();
        panelRound7 = new component.PanelRound();
        jTextFieldNgayVaoLam = new javax.swing.JTextField();
        gioiTinh = new javax.swing.JLabel();
        vaiTro = new javax.swing.JLabel();
        trangThai = new javax.swing.JLabel();
        panelRound9 = new component.PanelRound();
        jComboBox1 = new javax.swing.JComboBox<>();
        maNhanVien = new javax.swing.JLabel();
        panelRound1 = new component.PanelRound();
        jTextFieldMaNhanVien = new javax.swing.JTextField();
        diaChi = new javax.swing.JLabel();
        panelRound12 = new component.PanelRound();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNhanVienQuanLy = new javax.swing.JRadioButton();
        jRadioButtonNhanVien = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(83, 86, 99));

        panelRound2.setBackground(new java.awt.Color(31, 29, 43));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Họ tên", "Tuổi", "Số điện thoại", "Ngày vào làm", "Giới tính", "Vai trò", "Trạng thái", "Mã nhân viên", "Địa chỉ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        fromDateJLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fromDateJLabel.setForeground(new java.awt.Color(255, 255, 255));
        fromDateJLabel.setText("QUẢN LÝ NHÂN VIÊN");

        panelRound3.setBackground(new java.awt.Color(31, 29, 43));
        panelRound3.setForeground(new java.awt.Color(31, 29, 43));
        panelRound3.setToolTipText("");
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound3MouseExited(evt);
            }
        });

        hoTen.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        hoTen.setForeground(new java.awt.Color(255, 255, 255));
        hoTen.setText("Họ và tên ");
        hoTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoTenMouseClicked(evt);
            }
        });

        ngayVaoLam.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        ngayVaoLam.setForeground(new java.awt.Color(255, 255, 255));
        ngayVaoLam.setText("Ngày vào làm");
        ngayVaoLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ngayVaoLamMouseClicked(evt);
            }
        });

        tuoi.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        tuoi.setForeground(new java.awt.Color(255, 255, 255));
        tuoi.setText("Tuổi");
        tuoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuoiMouseClicked(evt);
            }
        });

        soDienThoai.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        soDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        soDienThoai.setText("Số điện thoại");
        soDienThoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soDienThoaiMouseClicked(evt);
            }
        });

        JButtonAdd.setBackground(new java.awt.Color(51, 204, 0));
        JButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        JButtonAdd.setText("THÊM NHÂN VIÊN");
        JButtonAdd.setColor(new java.awt.Color(51, 204, 0));
        JButtonAdd.setColorClick(new java.awt.Color(179, 250, 160));
        JButtonAdd.setColorOver(new java.awt.Color(51, 204, 0));
        JButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonAddMouseClicked(evt);
            }
        });
        JButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddActionPerformed(evt);
            }
        });

        JButtonUpdate.setBackground(new java.awt.Color(255, 51, 0));
        JButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        JButtonUpdate.setText("SỬA THÔNG TIN");
        JButtonUpdate.setColor(new java.awt.Color(255, 51, 0));
        JButtonUpdate.setColorClick(new java.awt.Color(255, 102, 102));
        JButtonUpdate.setColorOver(new java.awt.Color(255, 51, 0));
        JButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonUpdateMouseClicked(evt);
            }
        });
        JButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonUpdateActionPerformed(evt);
            }
        });

        jTextFieldHoTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldHoTenMouseExited(evt);
            }
        });
        jTextFieldHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldHoTen)
        );

        jTextFieldSoDienThoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSoDienThoaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                none(evt);
            }
        });
        jTextFieldSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoDienThoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextFieldSoDienThoai)
                .addGap(0, 0, 0))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jTextFieldTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextFieldTuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldTuoi)
        );

        jTextFieldNgayVaoLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNgayVaoLamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addComponent(jTextFieldNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNgayVaoLam)
        );

        gioiTinh.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        gioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        gioiTinh.setText("Giới tính");
        gioiTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gioiTinhMouseClicked(evt);
            }
        });

        vaiTro.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        vaiTro.setForeground(new java.awt.Color(255, 255, 255));
        vaiTro.setText("Vai trò ");
        vaiTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaiTroMouseClicked(evt);
            }
        });

        trangThai.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        trangThai.setForeground(new java.awt.Color(255, 255, 255));
        trangThai.setText("Trạng thái");
        trangThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangThaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 159, Short.MAX_VALUE)
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1)
        );

        maNhanVien.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        maNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        maNhanVien.setText("Mã nhân viên");
        maNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maNhanVienMouseClicked(evt);
            }
        });

        jTextFieldMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(jTextFieldMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        diaChi.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        diaChi.setForeground(new java.awt.Color(255, 255, 255));
        diaChi.setText("Địa chỉ");
        diaChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diaChiMouseClicked(evt);
            }
        });

        jTextFieldDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiaChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound12Layout.createSequentialGroup()
                .addComponent(jTextFieldDiaChi)
                .addGap(0, 0, 0))
        );

        jRadioButtonNu.setForeground(new java.awt.Color(242, 242, 242));
        jRadioButtonNu.setText("Nữ");
        jRadioButtonNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNuActionPerformed(evt);
            }
        });

        jRadioButtonNam.setForeground(new java.awt.Color(242, 242, 242));
        jRadioButtonNam.setText("Nam");
        jRadioButtonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNamActionPerformed(evt);
            }
        });

        jRadioButtonNhanVienQuanLy.setForeground(new java.awt.Color(242, 242, 242));
        jRadioButtonNhanVienQuanLy.setText("Nhân viên Quản lý");

        jRadioButtonNhanVien.setForeground(new java.awt.Color(242, 242, 242));
        jRadioButtonNhanVien.setText("Nhân viên phục vụ");
        jRadioButtonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonNhanVienQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(soDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(trangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(ngayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(JButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRound12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(panelRound12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(jRadioButtonNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(jRadioButtonNhanVienQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addComponent(fromDateJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addComponent(fromDateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonAddActionPerformed

    private void JButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonUpdateActionPerformed

    private void hoTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoTenMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_hoTenMouseClicked

    private void ngayVaoLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ngayVaoLamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayVaoLamMouseClicked

    private void tuoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tuoiMouseClicked

    private void soDienThoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soDienThoaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_soDienThoaiMouseClicked

    private void jTextFieldHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoTenActionPerformed

    private void jTextFieldTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTuoiActionPerformed

    private void jTextFieldNgayVaoLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayVaoLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNgayVaoLamActionPerformed

    private void JButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonAddMouseClicked
        // TODO add your handling code here:
        int tuoi = Integer.parseInt(jTextFieldTuoi.getText());

        Boolean gioiTinh = null;
        if (jRadioButtonNam.isSelected()) {
            gioiTinh = true;
        } else if (jRadioButtonNu.isSelected()) {
            gioiTinh = false;
        }

        utils.Enum.LoaiVaiTro vaiTro = null;
        if (jRadioButtonNhanVienQuanLy.isSelected()) {
            vaiTro = utils.Enum.LoaiVaiTro.NHAN_VIEN_QL;
        } else if (jRadioButtonNhanVien.isSelected()) {
            vaiTro = utils.Enum.LoaiVaiTro.NHAN_VIEN_PHUC_VU;
        }

        boolean trangThai = true;
        if (jComboBox1.getSelectedItem().toString().equals("Đang làm")) {
            trangThai = true;
        } else if (jComboBox1.getSelectedItem().toString().equals("Đang nghĩ làm")) {
            trangThai = false;
        }

        NhanVien nv = new NhanVien();
        nv.setHoTen(jTextFieldHoTen.getText());
        nv.setTuoi(tuoi);
        nv.setSoDienThoai(jTextFieldSoDienThoai.getText());
        nv.setNgayBatDauLam(LocalDateTime.now());
        nv.setDiaChi(jTextFieldDiaChi.getText());
        nv.setVaiTro(vaiTro);
        nv.setTrangThai(true);
        nv.setGioiTinh(gioiTinh);
        nv.setTrangThai(trangThai);
        nv.setMaNV(jTextFieldMaNhanVien.getText());
        if (daoNV.insert(nv)) {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 1500, "Thêm nhân viên thành công !");
            populateTable();
            clearData();
            addTaiKhoan(nv);
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 1500, "Thêm tài khoản thành công !");

        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Chưa được thêm nhân viên!");

        }
    }//GEN-LAST:event_JButtonAddMouseClicked

    private void jTextFieldHoTenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHoTenMouseExited


    }//GEN-LAST:event_jTextFieldHoTenMouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        List<NhanVien> allNhanVien = daoNV.findAll(NhanVien.class);
        // Lấy chỉ số của hàng được chọn
        int rowIndex = jTable1.getSelectedRow();

        // Kiểm tra nếu hàng được chọn hợp lệ
        if (rowIndex >= 0) {
            // Lấy đối tượng NhanVien từ hàng được chọn
            NhanVien nv = allNhanVien.get(rowIndex);

            // Hiển thị dữ liệu của đối tượng NhanVien lên các JTextField tương ứng
            jTextFieldHoTen.setText(nv.getHoTen());
            jTextFieldTuoi.setText(String.valueOf(nv.getTuoi()));
            jTextFieldSoDienThoai.setText(nv.getSoDienThoai());
            jTextFieldDiaChi.setText(nv.getDiaChi());
            jTextFieldMaNhanVien.setText(nv.getMaNV());

            // Chuyển đổi ngày bắt đầu làm việc từ LocalDateTime sang LocalDate và hiển thị lên JTextField
            jTextFieldNgayVaoLam.setText(nv.getNgayBatDauLam().toLocalDate().toString());

            // Chuyển đổi giới tính từ boolean sang chuỗi và hiển thị lên JTextField
            if (nv.isGioiTinh()) {
                jRadioButtonNam.setSelected(true);
                jRadioButtonNu.setSelected(false);
            } else {
                jRadioButtonNam.setSelected(false);
                jRadioButtonNu.setSelected(true);
            }
            // Hiển thị vai trò của nhân viên lên JTextField
            if (nv.getVaiTro().equals(utils.Enum.LoaiVaiTro.NHAN_VIEN_QL)) {
                jRadioButtonNhanVienQuanLy.setSelected(true);
                jRadioButtonNhanVien.setSelected(false);
            } else {
                jRadioButtonNam.setSelected(false);
                jRadioButtonNu.setSelected(true);
            }
            // Chuyển đổi trạng thái từ boolean sang chuỗi và hiển thị lên JTextField
            if (nv.isTrangThai()) {
                jComboBox1.setSelectedItem("Đang làm");
            } else {
                jComboBox1.setSelectedItem("Đã nghĩ làm");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void JButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonUpdateMouseClicked
        // TODO add your handling code here:
        int tuoi;
        try {
            tuoi = Integer.parseInt(jTextFieldTuoi.getText());
            if (tuoi < 18) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1500, "Nhân viên phải >= 18 tuổi!");
                return;
            }
        } catch (NumberFormatException e) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Tuổi phải là một số nguyên hợp lệ!");
            return;
        }

        // Kiểm tra họ tên không được rỗng
        String hoTen = jTextFieldHoTen.getText();
        if (hoTen.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1500, "Họ tên không được rỗng!");
            return;
        }

        // Kiểm tra số điện thoại
        String soDienThoai = jTextFieldSoDienThoai.getText();
        if (!soDienThoai.matches("^(03|05|07|08|09)\\d{8}$")) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Số điện thoại không hợp lệ! Phải bắt đầu bằng 03, 05, 07, 08, 09 và có 10 số.");
            return;
        }

        // Kiểm tra ngày bắt đầu làm việc
        LocalDateTime ngayBatDauLam = LocalDateTime.now();  // Hoặc nhận từ một input nào đó nếu cần
        if (ngayBatDauLam.isAfter(LocalDateTime.now())) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Ngày bắt đầu làm việc không được vượt quá ngày hiện tại!");
            return;
        }

        // Kiểm tra địa chỉ không được rỗng
        String diaChi = jTextFieldDiaChi.getText();
        if (diaChi.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1500, "Địa chỉ không được rỗng!");
            return;
        }

        // Tạo đối tượng NhanVien và cập nhật thông tin
        NhanVien nv = new NhanVien();
        nv.setHoTen(hoTen);
        nv.setTuoi(tuoi);
        nv.setSoDienThoai(soDienThoai);
        nv.setNgayBatDauLam(ngayBatDauLam);
        nv.setDiaChi(diaChi);

        // Cập nhật thông tin nhân viên
        if (daoNV.update(nv)) {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, 1500, "Cập nhật thông tin nhân viên thành công!");
            populateTable();  // Giả sử phương thức này cập nhật lại bảng hiển thị nhân viên
            clearData();      // Giả sử phương thức này xóa dữ liệu trong các trường nhập
        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_RIGHT, 1500, "Cập nhật thông tin nhân viên thất bại!");
        }
    }//GEN-LAST:event_JButtonUpdateMouseClicked

    private void gioiTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gioiTinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gioiTinhMouseClicked

    private void vaiTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaiTroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vaiTroMouseClicked

    private void trangThaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangThaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trangThaiMouseClicked

    private void jTextFieldSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoDienThoaiActionPerformed

    private void maNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maNhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maNhanVienMouseClicked

    private void jTextFieldMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaNhanVienActionPerformed

    private void diaChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diaChiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiMouseClicked

    private void jTextFieldDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaChiActionPerformed

    private void jRadioButtonNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNuActionPerformed

    private void jRadioButtonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNamActionPerformed

    private void jRadioButtonNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNhanVienActionPerformed

    private void panelRound3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseExited
        // TODO add your handling code here:
        /*
        * NVabbddmmyyxxx Trong đó : a là giới tính (nam là 1, nữ là 0) bb là tuổi
        * của nhân viên lúc vào làm dd là ngày vào làm mm là tháng vào làm yy là 2
         * số cuối của năm vào làm xxx là 3 số đuôi của số điện thoại.
        *    
         */
        String gioiTinh = "";
        if (jRadioButtonNam.isSelected()) {
            gioiTinh = "1";
        } else {
            gioiTinh = "0";
        }

        String vaiTro = "";
        if (jRadioButtonNhanVienQuanLy.isSelected()) {
            vaiTro = "1";
        } else {
            vaiTro = "0";
        }

        String tuoi = jTextFieldTuoi.getText();
        String ngay = String.valueOf(LocalDateTime.now().getDayOfMonth());
        String thang = String.valueOf(LocalDateTime.now().getMonthValue());
        String nam = String.valueOf(LocalDateTime.now().getYear() - 2000);
        String sdt = jTextFieldSoDienThoai.getText();

        // Kiểm tra nếu các trường không rỗng
        if (!gioiTinh.isEmpty() || !tuoi.isEmpty() || !sdt.isEmpty()) {
            String maNhanVien = "NV" + gioiTinh + tuoi + vaiTro + ngay + thang + nam + sdt.substring(7);
            jTextFieldMaNhanVien.setText(maNhanVien);
        }

    }//GEN-LAST:event_panelRound3MouseExited

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:

    }//GEN-LAST:event_none

    private void jTextFieldSoDienThoaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSoDienThoaiMouseEntered
        // TODO add your handling code here:
        jTextFieldNgayVaoLam.setText(LocalDateTime.now().toLocalDate().toString());
    }//GEN-LAST:event_jTextFieldSoDienThoaiMouseEntered

    private NhanVienDAO daoNV;
    private TaiKhoanDAO daoTK;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton JButtonAdd;
    private component.MyButton JButtonUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel diaChi;
    private javax.swing.JLabel fromDateJLabel;
    private javax.swing.JLabel gioiTinh;
    private javax.swing.JLabel hoTen;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNhanVien;
    private javax.swing.JRadioButton jRadioButtonNhanVienQuanLy;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldMaNhanVien;
    private javax.swing.JTextField jTextFieldNgayVaoLam;
    private javax.swing.JTextField jTextFieldSoDienThoai;
    private javax.swing.JTextField jTextFieldTuoi;
    private javax.swing.JLabel maNhanVien;
    private javax.swing.JLabel ngayVaoLam;
    private component.PanelRound panelRound1;
    private component.PanelRound panelRound12;
    private component.PanelRound panelRound2;
    private component.PanelRound panelRound3;
    private component.PanelRound panelRound4;
    private component.PanelRound panelRound5;
    private component.PanelRound panelRound6;
    private component.PanelRound panelRound7;
    private component.PanelRound panelRound9;
    private javax.swing.JLabel soDienThoai;
    private javax.swing.JLabel trangThai;
    private javax.swing.JLabel tuoi;
    private javax.swing.JLabel vaiTro;
    // End of variables declaration//GEN-END:variables
}
