package view.manager.forms;

import dao.imlp.BanDAO;
import entity.Ban;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import view.manager.components.SimpleForm;


/**
 * @author RAVEN
 */
public class GD_QuanLyBan extends SimpleForm {

    /**
     * Creates new form ReadForm
     */
    public GD_QuanLyBan() {
        initComponents();
        daoB = new BanDAO();
        populateTable();
    }

    private void populateTable() {
        // Xóa tất cả các dòng hiện có trong bảng
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);

        List<Ban> allBans = daoB.findAll(Ban.class);

        // Thêm dữ liệu từ danh sách vào bảng
        for (int i = 0; i < allBans.size(); i++) {
            Ban ban = allBans.get(i);
            // Truy cập các thuộc tính của đối tượng Ban và thêm vào từng cột
            model.addRow(new Object[]{i + 1, ban.getMaBan(), ban.getSoGhe(), ban.getTrangThai(), ban.getTang()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new component.PanelRound();
        fromDateJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new view.manger.table.Table();

        setBackground(new java.awt.Color(83, 86, 99));

        panelRound2.setBackground(new java.awt.Color(31, 29, 43));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        fromDateJLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fromDateJLabel.setForeground(new java.awt.Color(255, 255, 255));
        fromDateJLabel.setText("QUẢN LÝ BÀN");

        table1.setAutoCreateRowSorter(true);
        table1.setBackground(new java.awt.Color(83, 86, 99));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã bàn", "Số người", "Trạng thái", "Tầng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromDateJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1939, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addComponent(fromDateJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private BanDAO daoB;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fromDateJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private component.PanelRound panelRound2;
    private view.manger.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
