/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import LIB.FadeEffect;
import component.OrderItem;
import component.ScrollBarCustom;
import component.WrapGridLayout;
import component.WrapLayout;
import entity.HoaDon;
import icon.FontAwesome;
import java.awt.Color;
import jiconfont.swing.IconFontSwing;
import javax.swing.*;
import java.awt.*;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Laptop
 */
public class GD_ThanhToan extends javax.swing.JPanel {

    /**
     * Creates new form GD_ThanhToan
     */
//    set width for first
    private HoaDon hoaDon;

    public GD_ThanhToan(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
        initComponents();
        IconFontSwing.register(FontAwesome.getIconFont());
        theThanhVienLabel.setIcon(IconFontSwing.buildIcon(FontAwesome.CREDIT_CARD, 20, Color.WHITE));
        chuongTrinhKhuyenMai.setIcon(IconFontSwing.buildIcon(FontAwesome.GIFT, 20, Color.WHITE));
        btnAddKM.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS, 20, Color.WHITE));
        btnDown.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_DOWN, 10, Color.WHITE));
        btnUp.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_UP, 10, Color.WHITE));
        btnDownTable.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_DOWN, 10, Color.WHITE));
        btnUpTable.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_UP, 10, Color.WHITE));
        btnBack.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_LEFT, 10, Color.WHITE));
        btnScanQR.setIcon(IconFontSwing.buildIcon(FontAwesome.QRCODE, 20, Color.WHITE));
        khuyenMai.setIcon(IconFontSwing.buildIcon(FontAwesome.TAG, 20, Color.WHITE));
        iconSearch.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH, 20));
        iconSearch_KM.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH, 20));
        maHoaDon.setIcon(IconFontSwing.buildIcon(FontAwesome.PENCIL, 20, Color.WHITE));
        txtMTV.setBackground(new Color(0, 0, 0, 0));
        txtMKM.setBackground(new Color(0, 0, 0, 0));
        tableContainer.setLayout(new WrapLayout(FlowLayout.LEADING, 0, 0));
        tableBody.setVerticalScrollBar(new ScrollBarCustom());
        tableBody.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        FirstTimeLoadItem();
    }

    private void FirstTimeLoadItem() {
        Timer timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Thêm mã để kích hoạt action listener tại đây
                loadData();
                tableContainer.repaint();
                tableContainer.revalidate();
            }
        });
        timer.setRepeats(false); // Chỉ chạy một lần sau 5 giây
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftContainer = new javax.swing.JPanel();
        theThanhVienContainer = new javax.swing.JPanel();
        theThanhVienLabel = new javax.swing.JLabel();
        maTheContainer = new component.PanelRound();
        txtMTV = new javax.swing.JTextField();
        iconSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maTheContainer1 = new component.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        maTheContainer2 = new component.PanelRound();
        ctkmContainer = new javax.swing.JPanel();
        chuongTrinhKhuyenMai = new javax.swing.JLabel();
        btnAddKM = new component.MyButton();
        btnDown = new component.MyButton();
        btnUp = new component.MyButton();
        ctkmContainer1 = new javax.swing.JPanel();
        khuyenMai = new javax.swing.JLabel();
        maTheContainer3 = new component.PanelRound();
        txtMKM = new javax.swing.JTextField();
        iconSearch_KM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnScanQR = new component.MyButton();
        rightContainer = new javax.swing.JPanel();
        theThanhVienContainer1 = new javax.swing.JPanel();
        maHoaDon = new javax.swing.JLabel();
        maHoaDon1 = new javax.swing.JLabel();
        btnBack = new component.MyButton();
        jPanel2 = new javax.swing.JPanel();
        btnReserve = new component.MyButton();
        btnThuTien = new component.MyButton();
        btnLuuTam = new component.MyButton();
        btnReserve3 = new component.MyButton();
        btnUpTable = new component.MyButton();
        btnDownTable = new component.MyButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        table = new javax.swing.JPanel();
        headerTable = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tableBody = new javax.swing.JScrollPane();
        tableContainer = new javax.swing.JPanel();

        leftContainer.setBackground(new java.awt.Color(83, 86, 99));

        theThanhVienContainer.setBackground(new java.awt.Color(31, 29, 43));

        theThanhVienLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        theThanhVienLabel.setForeground(new java.awt.Color(255, 255, 255));
        theThanhVienLabel.setText("Thể thành viên");

        javax.swing.GroupLayout theThanhVienContainerLayout = new javax.swing.GroupLayout(theThanhVienContainer);
        theThanhVienContainer.setLayout(theThanhVienContainerLayout);
        theThanhVienContainerLayout.setHorizontalGroup(
            theThanhVienContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theThanhVienContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(theThanhVienLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        theThanhVienContainerLayout.setVerticalGroup(
            theThanhVienContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theThanhVienContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(theThanhVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        maTheContainer.setBackground(new java.awt.Color(255, 255, 255));
        maTheContainer.setRoundBottomLeft(8);
        maTheContainer.setRoundBottomRight(8);
        maTheContainer.setRoundTopLeft(8);
        maTheContainer.setRoundTopRight(8);

        txtMTV.setBorder(null);
        txtMTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maTheContainerLayout = new javax.swing.GroupLayout(maTheContainer);
        maTheContainer.setLayout(maTheContainerLayout);
        maTheContainerLayout.setHorizontalGroup(
            maTheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maTheContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMTV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        maTheContainerLayout.setVerticalGroup(
            maTheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMTV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã thành viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Thành viên");

        maTheContainer1.setBackground(new java.awt.Color(255, 255, 255));
        maTheContainer1.setRoundBottomLeft(8);
        maTheContainer1.setRoundBottomRight(8);
        maTheContainer1.setRoundTopLeft(8);
        maTheContainer1.setRoundTopRight(8);

        javax.swing.GroupLayout maTheContainer1Layout = new javax.swing.GroupLayout(maTheContainer1);
        maTheContainer1.setLayout(maTheContainer1Layout);
        maTheContainer1Layout.setHorizontalGroup(
            maTheContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        maTheContainer1Layout.setVerticalGroup(
            maTheContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hạng Thẻ");

        maTheContainer2.setBackground(new java.awt.Color(255, 255, 255));
        maTheContainer2.setRoundBottomLeft(8);
        maTheContainer2.setRoundBottomRight(8);
        maTheContainer2.setRoundTopLeft(8);
        maTheContainer2.setRoundTopRight(8);

        javax.swing.GroupLayout maTheContainer2Layout = new javax.swing.GroupLayout(maTheContainer2);
        maTheContainer2.setLayout(maTheContainer2Layout);
        maTheContainer2Layout.setHorizontalGroup(
            maTheContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        maTheContainer2Layout.setVerticalGroup(
            maTheContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        ctkmContainer.setBackground(new java.awt.Color(31, 29, 43));

        chuongTrinhKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chuongTrinhKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        chuongTrinhKhuyenMai.setText("Chương trình khuyến mãi");

        javax.swing.GroupLayout ctkmContainerLayout = new javax.swing.GroupLayout(ctkmContainer);
        ctkmContainer.setLayout(ctkmContainerLayout);
        ctkmContainerLayout.setHorizontalGroup(
            ctkmContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(chuongTrinhKhuyenMai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ctkmContainerLayout.setVerticalGroup(
            ctkmContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chuongTrinhKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAddKM.setForeground(new java.awt.Color(255, 255, 255));
        btnAddKM.setText("KHUYẾN MÃI KHÁC");
        btnAddKM.setColor(new java.awt.Color(31, 29, 43));
        btnAddKM.setColorClick(new java.awt.Color(234, 124, 105));
        btnAddKM.setColorOver(new java.awt.Color(234, 124, 105));
        btnAddKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddKM.setRadius(8);
        btnAddKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKMActionPerformed(evt);
            }
        });

        btnDown.setForeground(new java.awt.Color(255, 255, 255));
        btnDown.setColor(new java.awt.Color(31, 29, 43));
        btnDown.setColorClick(new java.awt.Color(234, 124, 105));
        btnDown.setColorOver(new java.awt.Color(234, 124, 105));
        btnDown.setRadius(8);
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        btnUp.setForeground(new java.awt.Color(255, 255, 255));
        btnUp.setColor(new java.awt.Color(31, 29, 43));
        btnUp.setColorClick(new java.awt.Color(234, 124, 105));
        btnUp.setColorOver(new java.awt.Color(234, 124, 105));
        btnUp.setRadius(8);
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        ctkmContainer1.setBackground(new java.awt.Color(31, 29, 43));

        khuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        khuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        khuyenMai.setText("Mã khuyến mãi");

        maTheContainer3.setBackground(new java.awt.Color(255, 255, 255));
        maTheContainer3.setRoundBottomLeft(8);
        maTheContainer3.setRoundBottomRight(8);
        maTheContainer3.setRoundTopLeft(8);
        maTheContainer3.setRoundTopRight(8);

        txtMKM.setBorder(null);
        txtMKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maTheContainer3Layout = new javax.swing.GroupLayout(maTheContainer3);
        maTheContainer3.setLayout(maTheContainer3Layout);
        maTheContainer3Layout.setHorizontalGroup(
            maTheContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maTheContainer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSearch_KM, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        maTheContainer3Layout.setVerticalGroup(
            maTheContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconSearch_KM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout ctkmContainer1Layout = new javax.swing.GroupLayout(ctkmContainer1);
        ctkmContainer1.setLayout(ctkmContainer1Layout);
        ctkmContainer1Layout.setHorizontalGroup(
            ctkmContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainer1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(khuyenMai)
                .addGap(31, 31, 31)
                .addComponent(maTheContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        ctkmContainer1Layout.setVerticalGroup(
            ctkmContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ctkmContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ctkmContainer1Layout.createSequentialGroup()
                        .addComponent(maTheContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(khuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(83, 86, 99));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        btnScanQR.setForeground(new java.awt.Color(255, 255, 255));
        btnScanQR.setText("Quét mã QR");
        btnScanQR.setColor(new java.awt.Color(31, 29, 43));
        btnScanQR.setColorClick(new java.awt.Color(234, 124, 105));
        btnScanQR.setColorOver(new java.awt.Color(234, 124, 105));
        btnScanQR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnScanQR.setRadius(8);
        btnScanQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftContainerLayout = new javax.swing.GroupLayout(leftContainer);
        leftContainer.setLayout(leftContainerLayout);
        leftContainerLayout.setHorizontalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theThanhVienContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ctkmContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ctkmContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addComponent(btnAddKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnScanQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(leftContainerLayout.createSequentialGroup()
                                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maTheContainer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maTheContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maTheContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(16, 16, 16))
            .addComponent(jScrollPane1)
        );
        leftContainerLayout.setVerticalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addComponent(theThanhVienContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maTheContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maTheContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maTheContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(15, 15, 15)
                .addComponent(btnScanQR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ctkmContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnAddKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(ctkmContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        rightContainer.setBackground(new java.awt.Color(83, 86, 99));
        rightContainer.setForeground(new java.awt.Color(255, 255, 255));

        theThanhVienContainer1.setBackground(new java.awt.Color(31, 29, 43));

        maHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        maHoaDon.setText("11122003-Ban101");
        maHoaDon.setToolTipText("");

        maHoaDon1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maHoaDon1.setForeground(new java.awt.Color(255, 255, 255));
        maHoaDon1.setText("13/3/2024 5:10 SA");
        maHoaDon1.setToolTipText("");

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setColor(new java.awt.Color(83, 86, 99));
        btnBack.setColorClick(new java.awt.Color(234, 124, 105));
        btnBack.setColorOver(new java.awt.Color(234, 124, 105));
        btnBack.setRadius(8);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout theThanhVienContainer1Layout = new javax.swing.GroupLayout(theThanhVienContainer1);
        theThanhVienContainer1.setLayout(theThanhVienContainer1Layout);
        theThanhVienContainer1Layout.setHorizontalGroup(
            theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, theThanhVienContainer1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maHoaDon1)
                .addContainerGap())
        );
        theThanhVienContainer1Layout.setVerticalGroup(
            theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theThanhVienContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(theThanhVienContainer1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(maHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(31, 29, 43));

        btnReserve.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve.setText("Đặt trước (0)");
        btnReserve.setToolTipText("");
        btnReserve.setColor(new java.awt.Color(83, 86, 99));
        btnReserve.setColorClick(new java.awt.Color(234, 124, 105));
        btnReserve.setColorOver(new java.awt.Color(234, 124, 105));
        btnReserve.setRadius(8);
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        btnThuTien.setForeground(new java.awt.Color(255, 255, 255));
        btnThuTien.setText("Thu tiền");
        btnThuTien.setToolTipText("");
        btnThuTien.setColor(new java.awt.Color(83, 86, 99));
        btnThuTien.setColorClick(new java.awt.Color(234, 124, 105));
        btnThuTien.setColorOver(new java.awt.Color(234, 124, 105));
        btnThuTien.setRadius(8);
        btnThuTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienActionPerformed(evt);
            }
        });

        btnLuuTam.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuTam.setText("Lưu tạm");
        btnLuuTam.setToolTipText("");
        btnLuuTam.setColor(new java.awt.Color(83, 86, 99));
        btnLuuTam.setColorClick(new java.awt.Color(234, 124, 105));
        btnLuuTam.setColorOver(new java.awt.Color(234, 124, 105));
        btnLuuTam.setRadius(8);
        btnLuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTamActionPerformed(evt);
            }
        });

        btnReserve3.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve3.setText("Đặt trước (0)");
        btnReserve3.setToolTipText("");
        btnReserve3.setColor(new java.awt.Color(83, 86, 99));
        btnReserve3.setColorClick(new java.awt.Color(234, 124, 105));
        btnReserve3.setColorOver(new java.awt.Color(234, 124, 105));
        btnReserve3.setRadius(8);
        btnReserve3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserve3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnReserve3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnLuuTam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnThuTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThuTien, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuTam, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnUpTable.setForeground(new java.awt.Color(255, 255, 255));
        btnUpTable.setColor(new java.awt.Color(31, 29, 43));
        btnUpTable.setColorClick(new java.awt.Color(234, 124, 105));
        btnUpTable.setColorOver(new java.awt.Color(234, 124, 105));
        btnUpTable.setRadius(8);
        btnUpTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpTableActionPerformed(evt);
            }
        });

        btnDownTable.setForeground(new java.awt.Color(255, 255, 255));
        btnDownTable.setColor(new java.awt.Color(31, 29, 43));
        btnDownTable.setColorClick(new java.awt.Color(234, 124, 105));
        btnDownTable.setColorOver(new java.awt.Color(234, 124, 105));
        btnDownTable.setRadius(8);
        btnDownTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownTableActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thành tiền:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Còn phải thu:");

        headerTable.setBackground(new java.awt.Color(31, 29, 43));
        headerTable.setLayout(new java.awt.GridLayout(1, 4));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Tên món");
        headerTable.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" SL");
        headerTable.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Đơn giá");
        headerTable.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thành tiền");
        headerTable.add(jLabel9);

        tableBody.setBackground(new java.awt.Color(83, 86, 99));
        tableBody.setBorder(null);

        tableContainer.setBackground(new java.awt.Color(83, 86, 99));

        javax.swing.GroupLayout tableContainerLayout = new javax.swing.GroupLayout(tableContainer);
        tableContainer.setLayout(tableContainerLayout);
        tableContainerLayout.setHorizontalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        tableContainerLayout.setVerticalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        tableBody.setViewportView(tableContainer);

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tableBody, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayout.createSequentialGroup()
                .addComponent(headerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tableBody, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightContainerLayout = new javax.swing.GroupLayout(rightContainer);
        rightContainer.setLayout(rightContainerLayout);
        rightContainerLayout.setHorizontalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theThanhVienContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpTable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDownTable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rightContainerLayout.setVerticalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addComponent(theThanhVienContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leftContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddKMActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpActionPerformed

    private void txtMTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMTVActionPerformed

    private void txtMKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKMActionPerformed

    private void btnScanQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanQRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScanQRActionPerformed

    private void btnUpTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpTableActionPerformed

    private void btnDownTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownTableActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnThuTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        jFrame.setUndecorated(true);
        jFrame.setExtendedState(MAXIMIZED_BOTH);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jFrame.add(new Form_ThuTien(jFrame));
        jFrame.setBackground(new Color(0, 0, 0, 0));
        FadeEffect.fadeInFrame(jFrame, 8, 0.1f);
        jFrame.setVisible(true);
    }//GEN-LAST:event_btnThuTienActionPerformed

    private void btnLuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTamActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnLuuTamActionPerformed

    private void btnReserve3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserve3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserve3ActionPerformed

    public void loadData() {
        int width = tableContainer.getWidth();
        OrderItem testOrderItemButton = new OrderItem(width, 1, new String[]{"Gỏi cuốn", "2", "400.000", "800.000"});
        tableContainer.add(testOrderItemButton);
        tableContainer.add(new OrderItem(width, 2, new String[]{"Cơm", "1", "400.000", "800.000"}));
        tableContainer.add(new OrderItem(width, 1, new String[]{"Bún Bò", "2", "400.000", "800.000"}));
        tableContainer.add(new OrderItem(width, 2, new String[]{"Phở Bò", "4", "400.000", "800.000"}));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btnAddKM;
    private component.MyButton btnBack;
    private component.MyButton btnDown;
    private component.MyButton btnDownTable;
    private component.MyButton btnLuuTam;
    private component.MyButton btnReserve;
    private component.MyButton btnReserve3;
    private component.MyButton btnScanQR;
    private component.MyButton btnThuTien;
    private component.MyButton btnUp;
    private component.MyButton btnUpTable;
    private javax.swing.JLabel chuongTrinhKhuyenMai;
    private javax.swing.JPanel ctkmContainer;
    private javax.swing.JPanel ctkmContainer1;
    private javax.swing.JPanel headerTable;
    private javax.swing.JLabel iconSearch;
    private javax.swing.JLabel iconSearch_KM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel khuyenMai;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JLabel maHoaDon;
    private javax.swing.JLabel maHoaDon1;
    private component.PanelRound maTheContainer;
    private component.PanelRound maTheContainer1;
    private component.PanelRound maTheContainer2;
    private component.PanelRound maTheContainer3;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel table;
    private javax.swing.JScrollPane tableBody;
    private javax.swing.JPanel tableContainer;
    private javax.swing.JPanel theThanhVienContainer;
    private javax.swing.JPanel theThanhVienContainer1;
    private javax.swing.JLabel theThanhVienLabel;
    private javax.swing.JTextField txtMKM;
    private javax.swing.JTextField txtMTV;
    // End of variables declaration//GEN-END:variables
}
