/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import entity.HoaDon;
import icon.FontAwesome;
import java.awt.Color;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author Laptop
 */
public class GD_ThanhToan extends javax.swing.JPanel {

    /**
     * Creates new form GD_ThanhToan
     */
    private HoaDon hoaDon;
    public GD_ThanhToan() {
        initComponents();
    }
    
    public GD_ThanhToan(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
        IconFontSwing.register(FontAwesome.getIconFont());
        initComponents();
        theThanhVienLabel.setIcon(IconFontSwing.buildIcon(FontAwesome.CREDIT_CARD, 20));
        chuongTrinhKhuyenMai.setIcon(IconFontSwing.buildIcon(FontAwesome.GIFT, 20));
        btnAddKM.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS, 20));
        btnDown.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_DOWN, 10, Color.WHITE));
        btnUp.setIcon(IconFontSwing.buildIcon(FontAwesome.CHEVRON_UP, 10, Color.WHITE));
        btnScanQR.setIcon(IconFontSwing.buildIcon(FontAwesome.QRCODE, 20));
        khuyenMai.setIcon(IconFontSwing.buildIcon(FontAwesome.TAG, 20));
        iconSearch.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH, 20));
        iconSearch_KM.setIcon(IconFontSwing.buildIcon(FontAwesome.SEARCH, 20));
        maHoaDon.setIcon(IconFontSwing.buildIcon(FontAwesome.PENCIL, 20));
        txtMTV.setBackground(new Color(0,0,0,0));
        txtMKM.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftContainer = new javax.swing.JPanel();
        theThanhVienContainer = new javax.swing.JPanel();
        theThanhVienLabel = new javax.swing.JLabel();
        maTheContainer = new component.PanelRound();
        txtMTV = new javax.swing.JTextField();
        iconSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maTheContainer1 = new component.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        maTheContainer2 = new component.PanelRound();
        ctkmContainer = new javax.swing.JPanel();
        chuongTrinhKhuyenMai = new javax.swing.JLabel();
        btnAddKM = new component.MyButton();
        btnDown = new component.MyButton();
        btnUp = new component.MyButton();
        ctkmContainer1 = new javax.swing.JPanel();
        khuyenMai = new javax.swing.JLabel();
        maTheContainer3 = new component.PanelRound();
        txtMKM = new javax.swing.JTextField();
        iconSearch_KM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnScanQR = new component.MyButton();
        rightContainer = new javax.swing.JPanel();
        theThanhVienContainer1 = new javax.swing.JPanel();
        maHoaDon = new javax.swing.JLabel();
        maHoaDon1 = new javax.swing.JLabel();
        btnUp2 = new component.MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnReserve = new component.MyButton();
        btnReserve1 = new component.MyButton();
        btnReserve2 = new component.MyButton();
        btnReserve3 = new component.MyButton();
        btnUp1 = new component.MyButton();
        btnDown1 = new component.MyButton();

        leftContainer.setBackground(new java.awt.Color(255, 255, 255));

        theThanhVienContainer.setBackground(new java.awt.Color(204, 204, 204));

        theThanhVienLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        theThanhVienLabel.setText("Thể thành viên");

        javax.swing.GroupLayout theThanhVienContainerLayout = new javax.swing.GroupLayout(theThanhVienContainer);
        theThanhVienContainer.setLayout(theThanhVienContainerLayout);
        theThanhVienContainerLayout.setHorizontalGroup(
            theThanhVienContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theThanhVienContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(theThanhVienLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        theThanhVienContainerLayout.setVerticalGroup(
            theThanhVienContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theThanhVienContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(theThanhVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        maTheContainer.setRoundBottomLeft(8);
        maTheContainer.setRoundBottomRight(8);
        maTheContainer.setRoundTopLeft(8);
        maTheContainer.setRoundTopRight(8);

        txtMTV.setBorder(null);
        txtMTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maTheContainerLayout = new javax.swing.GroupLayout(maTheContainer);
        maTheContainer.setLayout(maTheContainerLayout);
        maTheContainerLayout.setHorizontalGroup(
            maTheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maTheContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMTV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        maTheContainerLayout.setVerticalGroup(
            maTheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMTV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã thành viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên Thành viên");

        maTheContainer1.setRoundBottomLeft(8);
        maTheContainer1.setRoundBottomRight(8);
        maTheContainer1.setRoundTopLeft(8);
        maTheContainer1.setRoundTopRight(8);

        javax.swing.GroupLayout maTheContainer1Layout = new javax.swing.GroupLayout(maTheContainer1);
        maTheContainer1.setLayout(maTheContainer1Layout);
        maTheContainer1Layout.setHorizontalGroup(
            maTheContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        maTheContainer1Layout.setVerticalGroup(
            maTheContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hạng Thẻ");

        maTheContainer2.setRoundBottomLeft(8);
        maTheContainer2.setRoundBottomRight(8);
        maTheContainer2.setRoundTopLeft(8);
        maTheContainer2.setRoundTopRight(8);

        javax.swing.GroupLayout maTheContainer2Layout = new javax.swing.GroupLayout(maTheContainer2);
        maTheContainer2.setLayout(maTheContainer2Layout);
        maTheContainer2Layout.setHorizontalGroup(
            maTheContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        maTheContainer2Layout.setVerticalGroup(
            maTheContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        ctkmContainer.setBackground(new java.awt.Color(204, 204, 204));

        chuongTrinhKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chuongTrinhKhuyenMai.setText("Chương trình khuyến mãi");

        javax.swing.GroupLayout ctkmContainerLayout = new javax.swing.GroupLayout(ctkmContainer);
        ctkmContainer.setLayout(ctkmContainerLayout);
        ctkmContainerLayout.setHorizontalGroup(
            ctkmContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(chuongTrinhKhuyenMai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ctkmContainerLayout.setVerticalGroup(
            ctkmContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chuongTrinhKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAddKM.setText("KHUYẾN MÃI KHÁC");
        btnAddKM.setColor(new java.awt.Color(204, 204, 204));
        btnAddKM.setColorClick(new java.awt.Color(102, 102, 102));
        btnAddKM.setColorOver(new java.awt.Color(51, 51, 51));
        btnAddKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddKM.setRadius(8);
        btnAddKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKMActionPerformed(evt);
            }
        });

        btnDown.setForeground(new java.awt.Color(255, 255, 255));
        btnDown.setColor(new java.awt.Color(83, 86, 99));
        btnDown.setColorClick(new java.awt.Color(234, 124, 105));
        btnDown.setColorOver(new java.awt.Color(234, 124, 105));
        btnDown.setRadius(8);
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        btnUp.setForeground(new java.awt.Color(255, 255, 255));
        btnUp.setColor(new java.awt.Color(83, 86, 99));
        btnUp.setColorClick(new java.awt.Color(234, 124, 105));
        btnUp.setColorOver(new java.awt.Color(234, 124, 105));
        btnUp.setRadius(8);
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        ctkmContainer1.setBackground(new java.awt.Color(204, 204, 204));

        khuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        khuyenMai.setText("Mã khuyến mãi");

        maTheContainer3.setRoundBottomLeft(8);
        maTheContainer3.setRoundBottomRight(8);
        maTheContainer3.setRoundTopLeft(8);
        maTheContainer3.setRoundTopRight(8);

        txtMKM.setBorder(null);
        txtMKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maTheContainer3Layout = new javax.swing.GroupLayout(maTheContainer3);
        maTheContainer3.setLayout(maTheContainer3Layout);
        maTheContainer3Layout.setHorizontalGroup(
            maTheContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maTheContainer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSearch_KM, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        maTheContainer3Layout.setVerticalGroup(
            maTheContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconSearch_KM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout ctkmContainer1Layout = new javax.swing.GroupLayout(ctkmContainer1);
        ctkmContainer1.setLayout(ctkmContainer1Layout);
        ctkmContainer1Layout.setHorizontalGroup(
            ctkmContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainer1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(khuyenMai)
                .addGap(31, 31, 31)
                .addComponent(maTheContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        ctkmContainer1Layout.setVerticalGroup(
            ctkmContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctkmContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ctkmContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ctkmContainer1Layout.createSequentialGroup()
                        .addComponent(maTheContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(khuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        btnScanQR.setText("Quét mã QR");
        btnScanQR.setColor(new java.awt.Color(153, 153, 153));
        btnScanQR.setColorClick(new java.awt.Color(204, 204, 204));
        btnScanQR.setColorOver(new java.awt.Color(102, 102, 102));
        btnScanQR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnScanQR.setRadius(8);
        btnScanQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftContainerLayout = new javax.swing.GroupLayout(leftContainer);
        leftContainer.setLayout(leftContainerLayout);
        leftContainerLayout.setHorizontalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theThanhVienContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ctkmContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ctkmContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addComponent(btnAddKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnScanQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(leftContainerLayout.createSequentialGroup()
                                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maTheContainer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maTheContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maTheContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(16, 16, 16))
            .addComponent(jScrollPane1)
        );
        leftContainerLayout.setVerticalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addComponent(theThanhVienContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maTheContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maTheContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maTheContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(15, 15, 15)
                .addComponent(btnScanQR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ctkmContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(ctkmContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        rightContainer.setBackground(new java.awt.Color(255, 255, 255));

        theThanhVienContainer1.setBackground(new java.awt.Color(204, 204, 204));

        maHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maHoaDon.setText("11122003-Ban101");
        maHoaDon.setToolTipText("");

        maHoaDon1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maHoaDon1.setText("13/3/2024 5:10 SA");
        maHoaDon1.setToolTipText("");

        btnUp2.setForeground(new java.awt.Color(255, 255, 255));
        btnUp2.setColor(new java.awt.Color(83, 86, 99));
        btnUp2.setColorClick(new java.awt.Color(234, 124, 105));
        btnUp2.setColorOver(new java.awt.Color(234, 124, 105));
        btnUp2.setRadius(8);
        btnUp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout theThanhVienContainer1Layout = new javax.swing.GroupLayout(theThanhVienContainer1);
        theThanhVienContainer1.setLayout(theThanhVienContainer1Layout);
        theThanhVienContainer1Layout.setHorizontalGroup(
            theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, theThanhVienContainer1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maHoaDon1)
                .addContainerGap())
        );
        theThanhVienContainer1Layout.setVerticalGroup(
            theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theThanhVienContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(theThanhVienContainer1Layout.createSequentialGroup()
                        .addComponent(btnUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(theThanhVienContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(maHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnReserve.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve.setText("Đặt trước (0)");
        btnReserve.setToolTipText("");
        btnReserve.setColor(new java.awt.Color(83, 86, 99));
        btnReserve.setColorClick(new java.awt.Color(234, 124, 105));
        btnReserve.setColorOver(new java.awt.Color(234, 124, 105));
        btnReserve.setRadius(8);
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        btnReserve1.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve1.setText("Đặt trước (0)");
        btnReserve1.setToolTipText("");
        btnReserve1.setColor(new java.awt.Color(83, 86, 99));
        btnReserve1.setColorClick(new java.awt.Color(234, 124, 105));
        btnReserve1.setColorOver(new java.awt.Color(234, 124, 105));
        btnReserve1.setRadius(8);
        btnReserve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserve1ActionPerformed(evt);
            }
        });

        btnReserve2.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve2.setText("Đặt trước (0)");
        btnReserve2.setToolTipText("");
        btnReserve2.setColor(new java.awt.Color(83, 86, 99));
        btnReserve2.setColorClick(new java.awt.Color(234, 124, 105));
        btnReserve2.setColorOver(new java.awt.Color(234, 124, 105));
        btnReserve2.setRadius(8);
        btnReserve2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserve2ActionPerformed(evt);
            }
        });

        btnReserve3.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve3.setText("Đặt trước (0)");
        btnReserve3.setToolTipText("");
        btnReserve3.setColor(new java.awt.Color(83, 86, 99));
        btnReserve3.setColorClick(new java.awt.Color(234, 124, 105));
        btnReserve3.setColorOver(new java.awt.Color(234, 124, 105));
        btnReserve3.setRadius(8);
        btnReserve3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserve3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnReserve3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnReserve2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnReserve1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnUp1.setForeground(new java.awt.Color(255, 255, 255));
        btnUp1.setColor(new java.awt.Color(83, 86, 99));
        btnUp1.setColorClick(new java.awt.Color(234, 124, 105));
        btnUp1.setColorOver(new java.awt.Color(234, 124, 105));
        btnUp1.setRadius(8);
        btnUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUp1ActionPerformed(evt);
            }
        });

        btnDown1.setForeground(new java.awt.Color(255, 255, 255));
        btnDown1.setColor(new java.awt.Color(83, 86, 99));
        btnDown1.setColorClick(new java.awt.Color(234, 124, 105));
        btnDown1.setColorOver(new java.awt.Color(234, 124, 105));
        btnDown1.setRadius(8);
        btnDown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDown1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightContainerLayout = new javax.swing.GroupLayout(rightContainer);
        rightContainer.setLayout(rightContainerLayout);
        rightContainerLayout.setHorizontalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theThanhVienContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDown1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rightContainerLayout.setVerticalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addComponent(theThanhVienContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDown1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leftContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddKMActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpActionPerformed

    private void txtMTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMTVActionPerformed

    private void txtMKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKMActionPerformed

    private void btnScanQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanQRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScanQRActionPerformed

    private void btnUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUp1ActionPerformed

    private void btnDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDown1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDown1ActionPerformed

    private void btnUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUp2ActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnReserve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserve1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserve1ActionPerformed

    private void btnReserve2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserve2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserve2ActionPerformed

    private void btnReserve3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserve3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserve3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btnAddKM;
    private component.MyButton btnDown;
    private component.MyButton btnDown1;
    private component.MyButton btnReserve;
    private component.MyButton btnReserve1;
    private component.MyButton btnReserve2;
    private component.MyButton btnReserve3;
    private component.MyButton btnScanQR;
    private component.MyButton btnUp;
    private component.MyButton btnUp1;
    private component.MyButton btnUp2;
    private javax.swing.JLabel chuongTrinhKhuyenMai;
    private javax.swing.JPanel ctkmContainer;
    private javax.swing.JPanel ctkmContainer1;
    private javax.swing.JLabel iconSearch;
    private javax.swing.JLabel iconSearch_KM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel khuyenMai;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JLabel maHoaDon;
    private javax.swing.JLabel maHoaDon1;
    private component.PanelRound maTheContainer;
    private component.PanelRound maTheContainer1;
    private component.PanelRound maTheContainer2;
    private component.PanelRound maTheContainer3;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel theThanhVienContainer;
    private javax.swing.JPanel theThanhVienContainer1;
    private javax.swing.JLabel theThanhVienLabel;
    private javax.swing.JTextField txtMKM;
    private javax.swing.JTextField txtMTV;
    // End of variables declaration//GEN-END:variables
}
