/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.employee;

import com.formdev.flatlaf.FlatIntelliJLaf;
import dao.IHoaDonDAO;
import dao.ITheThanhVienDAO;
import dao.imlp.HoaDonDAO;
import dao.imlp.TheThanhVienDAO;
import entity.ChiTietKhuyenMai;
import entity.HoaDon;
import entity.KhuyenMai;
import entity.TheThanhVien;

import java.awt.Color;
import java.awt.Label;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import raven.toast.Notifications;

import static utils.AppUtils.*;

/**
 * @author Laptop
 */
public class Form_SuDungDiem extends javax.swing.JPanel {

    /**
     * Creates new form Form_SuDungDiem
     */
    private JFrame jFrame;
    private TheThanhVien theThanhVien;
    private ITheThanhVienDAO theThanhVienDAO = new TheThanhVienDAO();
    private List<String> loaiThe = List.of("STANDARD", "BRONZE", "SILVER", "GOLD", "DIAMOND");
    private JLabel tienPhaiThu;
    private JLabel thanhTienKMKhac;
    private List<HoaDon> hoaDons = new ArrayList<>();
    private double tongThanhToan = 0;
    private GD_ThanhToan gd_ThanhToan;

    public Form_SuDungDiem(JFrame jFrame, TheThanhVien theThanhVien) {
        this.jFrame = jFrame;
        this.theThanhVien = theThanhVien;
        Notifications.getInstance().setJFrame(jFrame);
        FlatIntelliJLaf.setup();
        initComponents();
        setBackground(new Color(0, 0, 0, 0.6f));
        setData();
    }

    private void setData() {
        if (theThanhVien != null) {
            thanhVien.setText(theThanhVien.getKhachHang().getHoTen());
            sdt.setText(theThanhVien.getKhachHang().getSoDienThoai());
            hangThe.setText(loaiThe.get(theThanhVien.getLoaiThe().ordinal()));
            diem.setText(((TheThanhVien) theThanhVienDAO.findById(theThanhVien.getMaThe(), TheThanhVien.class)).getDiemTich() + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new component.PanelRound();
        header = new component.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelRound3 = new component.PanelRound();
        myButton3 = new component.MyButton();
        myButton4 = new component.MyButton();
        container = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        thanhVien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hangThe = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelRound2 = new component.PanelRound();
        txtDiemSuDung = new javax.swing.JTextField();

        wrapper.setRoundBottomLeft(8);
        wrapper.setRoundBottomRight(8);
        wrapper.setRoundTopLeft(8);
        wrapper.setRoundTopRight(8);

        header.setBackground(new java.awt.Color(31, 29, 43));
        header.setRoundTopLeft(8);
        header.setRoundTopRight(8);

        jLabel1.setFont(utils.AppUtils.getFont(18f, _BOLD_));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sử dụng điểm");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_close.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(31, 29, 43));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);

        myButton3.setBackground(new java.awt.Color(83, 86, 99));
        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setText("ĐỒNG Ý");
        myButton3.setColor(new java.awt.Color(83, 86, 99));
        myButton3.setColorClick(new java.awt.Color(234, 124, 105));
        myButton3.setColorOver(new java.awt.Color(234, 124, 105));
        myButton3.setFont(utils.AppUtils.getFont(14f, _BOLD_));
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        myButton4.setBackground(new java.awt.Color(83, 86, 99));
        myButton4.setForeground(new java.awt.Color(255, 255, 255));
        myButton4.setText("HỦY BỎ");
        myButton4.setColor(new java.awt.Color(83, 86, 99));
        myButton4.setColorClick(new java.awt.Color(234, 124, 105));
        myButton4.setColorOver(new java.awt.Color(234, 124, 105));
        myButton4.setFont(utils.AppUtils.getFont(14f, _BOLD_));
        myButton4.setRadius(10);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        container.setBackground(new java.awt.Color(83, 86, 99));

        jLabel2.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thành viên");

        thanhVien.setFont(utils.AppUtils.getFont(16f, _BOLD_)
        );
        thanhVien.setForeground(new java.awt.Color(255, 255, 255));
        thanhVien.setText("Chị mộc nhiên");

        jLabel4.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số điện thoại");

        sdt.setFont(utils.AppUtils.getFont(16f, _BOLD_)
        );
        sdt.setForeground(new java.awt.Color(255, 255, 255));
        sdt.setText("0988788765");

        jLabel6.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hạng thẻ");

        hangThe.setFont(utils.AppUtils.getFont(16f, _BOLD_)
        );
        hangThe.setForeground(new java.awt.Color(255, 255, 255));
        hangThe.setText("Khách hàng thân thiết");

        jLabel8.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Điểm");

        diem.setFont(utils.AppUtils.getFont(16f, _BOLD_)
        );
        diem.setForeground(new java.awt.Color(255, 255, 255));
        diem.setText("0.0");

        jLabel10.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ưu đãi thẻ");

        jLabel12.setFont(utils.AppUtils.getFont(16f, _BOLD_)
        );
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dùng để thanh toán ");

        jLabel13.setFont(utils.AppUtils.getFont(16f, _BOLD_)
        );
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(50 điểm = 20.000 VND)");

        jLabel14.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Số điểm sử dụng");

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(8);
        panelRound2.setRoundBottomRight(8);
        panelRound2.setRoundTopLeft(8);
        panelRound2.setRoundTopRight(8);

        txtDiemSuDung.setBackground(new java.awt.Color(255, 255, 255));
        txtDiemSuDung.setFont(utils.AppUtils.getFont(16f, _NORMAL_)
        );
        txtDiemSuDung.setBorder(null);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDiemSuDung)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDiemSuDung, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hangThe, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diem, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(thanhVien))
                .addGap(24, 24, 24)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sdt))
                .addGap(24, 24, 24)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hangThe))
                .addGap(24, 24, 24)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(diem))
                .addGap(24, 24, 24)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(24, 24, 24)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        if (!txtDiemSuDung.getText().trim().equals("")) {
            try {
                if (Double.parseDouble(txtDiemSuDung.getText()) <= ((TheThanhVien) theThanhVienDAO.findById(theThanhVien.getMaThe(), TheThanhVien.class)).getDiemTich()) {
                    String ghiChu = theThanhVien.getKhachHang().getHoTen() + " sử dụng " + txtDiemSuDung.getText();
                    double thanhTienKM = (Double.parseDouble(txtDiemSuDung.getText()) * 20000 / 50);
                    HoaDon hoaDon = hoaDons.get(0);
                    KhuyenMai khuyenMai = new KhuyenMai("THE_THANH_VIEN", LocalDateTime.now(), LocalDateTime.now(), thanhTienKM, utils.Enum.LoaiKhuyenMai.SU_DUNG_DIEM, ghiChu);
                    ChiTietKhuyenMai chiTietKhuyenMai = new ChiTietKhuyenMai(hoaDon, khuyenMai);
                    hoaDon.getChiTietKhuyenMai().add(chiTietKhuyenMai);
                    hoaDon.tienPhaiThu();
                    hoaDon.getChiTietKhuyenMai().remove(chiTietKhuyenMai);
                    double thanhTienKhac = thanhTienKMKhac.getText().trim().equals("")
                            ? 0
                            : Double.parseDouble(thanhTienKMKhac.getText().replace("VNĐ", "").replace(",", ""));
                    this.thanhTienKMKhac.setText(FORMAT_MONEY.format(thanhTienKhac + thanhTienKM - gd_ThanhToan.getOldPoint()));
                    gd_ThanhToan.setOldPoint(thanhTienKM);
                    this.tienPhaiThu.setText(FORMAT_MONEY.format(tongThanhToan - Double.parseDouble(thanhTienKMKhac.getText().replace("VNĐ", "").replace(",", ""))));
                    theThanhVien.setDiemTich(theThanhVien.getDiemTich() - Double.parseDouble(txtDiemSuDung.getText()));
                    jFrame.setVisible(false);
                    jFrame.dispose();
                } else {
                    Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1000, "Điểm tích lũy không đủ");
                }
            } catch (Exception e) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1000, "Điểm tích lũy không hợp lệ");
            }
        } else {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, 1000, "Điểm tích lũy không hợp lệ");
        }
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
        jFrame.setVisible(false);
        jFrame.dispose();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        jFrame.setVisible(false);
        jFrame.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    public JLabel getTienPhaiThu() {
        return tienPhaiThu;
    }

    public void setTienPhaiThu(JLabel tienPhaiThu) {
        this.tienPhaiThu = tienPhaiThu;
    }

    public JLabel getThanhTienKMKhac() {
        return thanhTienKMKhac;
    }

    public void setThanhTienKMKhac(JLabel thanhTienKMKhac) {
        this.thanhTienKMKhac = thanhTienKMKhac;
    }

    public List<HoaDon> getHoaDons() {
        return hoaDons;
    }

    public void setHoaDons(List<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }

    public void setTongThanhToan(Double tongThanhToan) {
        this.tongThanhToan = tongThanhToan;
    }

    void setGDThanhToan(GD_ThanhToan aThis) {
        this.gd_ThanhToan = aThis;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel diem;
    private javax.swing.JLabel hangThe;
    private component.PanelRound header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private component.MyButton myButton3;
    private component.MyButton myButton4;
    private component.PanelRound panelRound2;
    private component.PanelRound panelRound3;
    private javax.swing.JLabel sdt;
    private javax.swing.JLabel thanhVien;
    private javax.swing.JTextField txtDiemSuDung;
    private component.PanelRound wrapper;
    // End of variables declaration//GEN-END:variables

}
