/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;
import icon.FontAwesome;
import java.awt.Color;
import java.awt.Dimension;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author Laptop
 */
public class BookingItem extends javax.swing.JPanel {

    /**
     * Creates new form BookingItem
     */
    public BookingItem() {
        initComponents();
//        wrapper.setSize(1076, 60);
        wrapper.setPreferredSize( new Dimension(1076, 60));
    }
    
    public BookingItem(int index, String[] data, int width) {
        initComponents();
        Color color = index % 2 != 0 ? new Color(83, 86, 99) : new Color(31, 29, 43);
        left.setBackground(color);
        right.setBackground(color);
        wrapper.setPreferredSize( new Dimension(width, 65));
        IconFontSwing.register(FontAwesome.getIconFont());
        btnNhanBan.setIcon(IconFontSwing.buildIcon(FontAwesome.CHECK_SQUARE_O, 40,new Color(20, 174, 92)));
        push(data);
    }
    
    private void push(String[] data) {
        gioDen.setText("   " + data[0]);
        khachHang.setText(data[1]);
        soNguoi.setText(data[2]);
        trangThai.setText(data[3]);
        datCoc.setText(data[4] + "    ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        myButton1 = new component.MyButton();
        myButton2 = new component.MyButton();
        btnNhanBan = new component.MyButton();
        gioDen = new javax.swing.JLabel();
        khachHang = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        soNguoi = new javax.swing.JLabel();
        trangThai = new javax.swing.JLabel();
        datCoc = new javax.swing.JLabel();

        wrapper.setForeground(new java.awt.Color(255, 255, 255));
        wrapper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrapperMouseClicked(evt);
            }
        });
        wrapper.setLayout(new java.awt.GridLayout(1, 0));

        left.setLayout(new java.awt.GridLayout(1, 5));

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/table_icon.png"))); // NOI18N
        myButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        myButton1.setMaximumSize(new java.awt.Dimension(30, 60));
        myButton1.setMinimumSize(new java.awt.Dimension(30, 60));
        myButton1.setName(""); // NOI18N
        myButton1.setRadius(12);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        left.add(myButton1);

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fork_icon.png"))); // NOI18N
        myButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        myButton2.setMaximumSize(new java.awt.Dimension(30, 60));
        myButton2.setMinimumSize(new java.awt.Dimension(30, 60));
        myButton2.setName(""); // NOI18N
        myButton2.setRadius(12);
        left.add(myButton2);

        btnNhanBan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNhanBan.setMaximumSize(new java.awt.Dimension(30, 60));
        btnNhanBan.setMinimumSize(new java.awt.Dimension(30, 60));
        btnNhanBan.setName(""); // NOI18N
        btnNhanBan.setRadius(12);
        left.add(btnNhanBan);

        gioDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gioDen.setForeground(new java.awt.Color(255, 255, 255));
        left.add(gioDen);

        khachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        khachHang.setForeground(new java.awt.Color(255, 255, 255));
        left.add(khachHang);

        wrapper.add(left);

        right.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        right.add(jLabel1);

        soNguoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soNguoi.setForeground(new java.awt.Color(255, 255, 255));
        soNguoi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        right.add(soNguoi);

        trangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trangThai.setForeground(new java.awt.Color(255, 255, 255));
        trangThai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        right.add(trangThai);

        datCoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datCoc.setForeground(new java.awt.Color(255, 255, 255));
        datCoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        right.add(datCoc);

        wrapper.add(right);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton1ActionPerformed

    private void wrapperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrapperMouseClicked
        // TODO add your handling code here:
        System.out.println(khachHang.getText());
    }//GEN-LAST:event_wrapperMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btnNhanBan;
    private javax.swing.JLabel datCoc;
    private javax.swing.JLabel gioDen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel khachHang;
    private javax.swing.JPanel left;
    private component.MyButton myButton1;
    private component.MyButton myButton2;
    private javax.swing.JPanel right;
    private javax.swing.JLabel soNguoi;
    private javax.swing.JLabel trangThai;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables


}
