/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import LIB.FadeEffect;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import utils.AppUtils;
import view.Form_DatBan;
import view.GD_DatMon;

/**
 *
 * @author dmx
 */
public class BanItem extends javax.swing.JPanel {

    /**
     * Creates new form BanItem
     */
    private JPanel main;
    private String type;
    private String image_type;
    private String maBan;

    public BanItem(String maBan, int trangThai, JPanel main, String type) {
        this.main = main;
        this.type = type;
        this.maBan = maBan;
        initComponents();
        jLabel1.setText(maBan);

        if (trangThai == utils.Enum.LoaiTrangThai.BAN_CO_KHACH.ordinal()) {
            image_type = "/images/my_table.png";
        } else if (trangThai == utils.Enum.LoaiTrangThai.BAN_DA_DUOC_DAT.ordinal()) {
            image_type = "/images/my_table_gray.png";
        } else if (trangThai == utils.Enum.LoaiTrangThai.BAN_TRONG.ordinal()) {
            image_type = "/images/my_table_blue.png";
        }

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_type)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        myButton1 = new component.MyButton();

        setBackground(new java.awt.Color(83, 86, 99));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("101");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 40));

        myButton1.setBackground(new java.awt.Color(83, 86, 99));
        myButton1.setBorder(null);
        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my_table.png"))); // NOI18N
        myButton1.setColor(new java.awt.Color(83, 86, 99));
        myButton1.setColorClick(new java.awt.Color(83, 86, 99));
        myButton1.setColorOver(new java.awt.Color(83, 86, 99));
        myButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myButton1MouseExited(evt);
            }
        });
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton1MouseEntered
        // TODO add your handling code here:
        // Load the image of the hand cursor
        ImageIcon handIcon = new ImageIcon("D:\\learning_university_IUH\\hoc_ky_6_(2023-2024)\\Phat_trien_ung_dung\\BaoCaoCK\\QuanLiDatBanNhaHang\\src\\main\\java\\icon\\icon_close.png"); // Thay đường dẫn này bằng đường dẫn thực sự của tệp hình ảnh của bạn

        // Create a custom cursor with the hand image
        Cursor handCursor = Toolkit.getDefaultToolkit().createCustomCursor(
                handIcon.getImage(), new Point(0, 0), "Hand Cursor");
        myButton1.setCursor(handCursor);
//        myButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_myButton1MouseEntered

    private void myButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton1MouseExited
        // TODO add your handling code here:
        myButton1.setBorder(null);
    }//GEN-LAST:event_myButton1MouseExited

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        switch (type) {
            case "DAT_BAN": {
                JFrame jFrame = new JFrame();
                jFrame.setUndecorated(true);
                jFrame.setExtendedState(MAXIMIZED_BOTH);
                jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                Form_DatBan form_DatBan = new Form_DatBan(jFrame);
                form_DatBan.setMainJpanel(main);
                jFrame.add(form_DatBan);
                jFrame.setBackground(new Color(0, 0, 0, 0));
                FadeEffect.fadeInFrame(jFrame, 8, 0.1f);
                jFrame.setVisible(true);
                break;
            }
            case "DAT_MON": {
                if (!image_type.equals("/images/my_table_gray.png")) {
                    AppUtils.setUI(main, new GD_DatMon(main, maBan));
                }
                break;
            }
        }
    }//GEN-LAST:event_myButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private component.MyButton myButton1;
    // End of variables declaration//GEN-END:variables
}
