/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import icon.FontAwesome;
import java.awt.Color;
import java.awt.Dimension;
import jiconfont.swing.IconFontSwing;
import javax.swing.Icon;
import view.Form_XemThucDon;

/**
 *
 * @author Laptop
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * Creates new form MenuItem
     */
    private Form_XemThucDon form;
    private String type;
    private int width;
    private String[] data;

    public MenuItem(int width, String[] data) {
        initComponents();
        this.width = width;
        this.data = data;
        wrapper.setBackground(new Color(83, 86, 99));
        right.setBackground(new Color(83, 86, 99));
        setPreferredSize(new Dimension(width - 2, 45));
        push(data);
    }

    public void push(String[] data) {
        tenMon.setText("  " + data[0] + "");
        soLuong.setText(data[1]);
    }

    private Icon getIconByType() {
        if (type.equals("THEM_MON")) {
            return IconFontSwing.buildIcon(FontAwesome.PLUS, 12, Color.WHITE);
        } else if (type.equals("HUY_MON")) {
            return IconFontSwing.buildIcon(FontAwesome.XING, 12, Color.WHITE);
        }
        return null;
    }

    public void setType(String type) {
        this.type = type;
        myButton1.setIcon(getIconByType());
    }

    public String[] getData() {
        return this.data;
    }

    public void setData(String[] data) {
        this.data = data;
        push(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        tenMon = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        soLuong = new javax.swing.JLabel();
        myButton1 = new component.MyButton();

        wrapper.setLayout(new java.awt.GridLayout(1, 0));

        tenMon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tenMon.setForeground(new java.awt.Color(255, 255, 255));
        wrapper.add(tenMon);

        soLuong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        soLuong.setForeground(new java.awt.Color(255, 255, 255));

        myButton1.setColor(new java.awt.Color(31, 29, 43));
        myButton1.setColorClick(new java.awt.Color(234, 124, 105));
        myButton1.setColorOver(new java.awt.Color(234, 124, 105));
        myButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        myButton1.setRadius(8);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(soLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(rightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addComponent(soLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        wrapper.add(right);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        if (type.equals("THEM_MON")) {
            form.themMon(new MenuItem(width, new String[]{data[0], "1"}));
        } else if (type.equals("HUY_MON")) {
            form.huyMon(this);
        }
    }//GEN-LAST:event_myButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton myButton1;
    private javax.swing.JPanel right;
    private javax.swing.JLabel soLuong;
    private javax.swing.JLabel tenMon;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables

    public void setForm(Form_XemThucDon form) {
        this.form = form;
    }
}
